node{
	
	stage('code build'){
	git 'https://github.com/preethijaz/travel-Project.git'
	}
	stage('build') {
	def mvnHome = tool name: 'maven3', type: 'maven'
	sh "${mvnHome}/mvn -f /var/lib/jenkins/workspace/travel-app/webapp/pom.xml clean install"
	}
	stage('deploy to tomcat') {
	sh "chmod -f 777 /var/lib/jenkins/workspace/travel-app/webapp/target/webapp.war"
	sh "cp -r /var/lib/jenkins/workspace/travel-app/webapp/target/webapp.war /apache-tomcat-9.0.56/webapps/"
	}
	}
